llm_workhorse: gpt-4.1-mini-2025-04-14
llm_flagship: gpt-4.1-2025-04-14
embeddings: text-embedding-3-small
embeddings_dim: 1536
vdb_index: space
retrieve_k: 3
name_dense: dense
name_sparse: sparse
model_sparse: "Qdrant/bm25"
